### ISSUE TITLE
We need to sync on the current state of the interface and the development process

### ISSUE THREAD

**Issue by zancas** [zancas/protoenv#6]
We need a howto that says:   Do x, Do y, now you are at the edge of `containenv` funcitonality.

Then people need to start walking through it, and making it (the howto) better, and filing issues which need to be added to the backlog.

**Comment by zancas** [comment]
This issue can close once the team has validated that they can run the functionality that `containenv` currently provides in a suitable development environment...  ( I can't wait 'til _that_ IS containenv! )

**Comment by zancas** [comment]
(0) In a development environment (I'm using the alpha-, alpha-, version of `containenv` called `prodactivity` for this)  open a terminal.
(1) `git clone https://github.com/zancas/containenv.git`

**Comment by zancas** [comment]
Please NOTE we're focused on Python 3.5.

We should document here any tips on environment set up.    Once you're happy with your environment and can run `containenv` remove yourself from the list of assignees.

**Comment by jputrino** [comment]
I pip installed in a container running the docker image I linked to in slack:
`pip install git+https://github.com/zancas/containenv.git`

**Comment by zancas** [comment]
@jputrino did you successfully run `containenv init`  it should print out a series of "OK" messages.

**Comment by zancas** [comment]
@jputrino Once it runs successfully in your container, we can close this issue.
