### ISSUE TITLE
containenv should be language-agnostic

### ISSUE THREAD

**Issue by jputrino** [zancas/protoenv#7]
virtualenv is for python projects.
Our alternative should, initially, inherently support python (3), go, & node.js. Other languages can be added later.

**Comment by jputrino** [comment]
First steps:
research what each of these languages uses to identify project dependencies (like the requirements file in python) so we know what we'll need to consult for things to install when creating a new containerenv.

**Comment by jputrino** [comment]
python -- requirements.txt
go -- see https://golang.org/doc/code.html && http://jbeckwith.com/2015/05/29/dependency-management-go/
node.js -- package.json; see https://devcenter.heroku.com/articles/node-best-practices

**Comment by zancas** [comment]
Nice work @jputrino.
